repos:
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.4.3
    hooks:
    -   id: style-files
        args: [--style_pkg=styler, --style_fun=tidyverse_style]
    -   id: lintr
    -   id: parsable-R
    -   id: no-browser-statement
    -   id: no-debug-statement
    -   id: deps-in-desc
    -   id: use-tidy-description
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: end-of-file-fixer
        exclude: '\.Rd$'
    -   id: trailing-whitespace
        exclude: '\.Rd$'
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=2000']
