library(ggplot2)
oscillo_theme_dark <- theme(panel.grid.major.y = element_line(color="black", linetype = "dotted"),
                            panel.grid.major.x = element_blank(),
                            panel.grid.minor   = element_blank(),
                            panel.background   = element_rect(fill="transparent"),
                            panel.border       = element_rect(linetype = "solid", fill = NA, color = "grey"),
                            axis.line          = element_blank(),
                            legend.position    = "none",
                            plot.background    = element_rect(fill="black"),
                            plot.margin        = unit(c(0,1,1,1), "lines"),
                            axis.title.y       = element_blank(),
                            axis.title.x       = element_text(size=14, color = "grey"),
                            axis.text          = element_text(size=14, color = "grey"),
                            axis.ticks         = element_line(color="grey"))

hot_theme_grid <- theme(panel.grid.major.y   = element_line(color="black", linetype = "dotted"),
                        panel.grid.major.x   = element_blank(),
                        panel.grid.minor     = element_blank(),
                        panel.background     = element_rect(fill="transparent"),
                        panel.border         = element_rect(linetype = "solid", fill = NA, color = "grey"),
                        axis.line            = element_blank(),
                        legend.position      = "right",
                        legend.justification = "right",
                        legend.background    = element_rect(fill="black"),
                        legend.key.width     = unit(50, "native"),
                        legend.title         = element_text(size=16, color="grey"),
                        legend.text          = element_text(size=16, color="grey"),
                        plot.background      = element_rect(fill="black"),
                        plot.margin          = margin(1,1,0,1, "lines"),
                        axis.title.x         = element_blank(),
                        axis.title.y         = element_text(size=16, color = "grey"),
                        axis.text            = element_text(size=16, color = "grey"),
                        axis.text.x          = element_blank(),
                        axis.ticks           = element_line(color="grey"))
